"""Cycle 073: exact counterexample to path-independent scalar revelation increments.

Classification: PROVED (finite-dimensional algebra), FALSIFIED (universal/path-independent
increment law), IMPORTED/KNOWN boundary (restricted measurement distinguishability).
"""
from fractions import Fraction

# Qubit pair rho0=|0><0|, rho1=|1><1| has Bloch-difference vector along Z.
# For resource spaces generated by Pauli directions, restricted binary distinction is
# 1/2 * ||projection(delta Bloch)||_2.  Here delta Bloch=(0,0,2), so values are exact.

def witness():
    # Chain A: constants -> {I,Z} -> {I,X,Z}
    chain_a = [Fraction(0), Fraction(1), Fraction(1)]
    # Chain B: constants -> {I,X} -> {I,X,Z}
    chain_b = [Fraction(0), Fraction(0), Fraction(1)]
    inc_a = [chain_a[i+1]-chain_a[i] for i in range(2)]
    inc_b = [chain_b[i+1]-chain_b[i] for i in range(2)]
    return {"chain_a": chain_a, "chain_b": chain_b,
            "increments_a": inc_a, "increments_b": inc_b}


def dimension_stress(n_max=12):
    # Embed the qubit witness as a 2D block in every n>=2 dimension.
    # The same projective measurement on that block gives the same exact separator.
    rows=[]
    for n in range(1,n_max+1):
        if n==1:
            rows.append((n,"DEGENERATE",Fraction(0),Fraction(0)))
        else:
            rows.append((n,"WITNESS",Fraction(1),Fraction(0)))
    return rows


def main():
    w=witness()
    assert w["increments_a"] == [Fraction(1),Fraction(0)]
    assert w["increments_b"] == [Fraction(0),Fraction(1)]
    assert sum(w["increments_a"]) == sum(w["increments_b"]) == 1
    rows=dimension_stress(12)
    assert all(r[1]=="WITNESS" for r in rows[1:])
    print("Cycle 073 exact witness PASS")
    print(w)
    print(rows)

if __name__ == "__main__":
    main()
