"""Cycle 100: two-generator coherence no-go for PDT dimension selection.

Candidate under test:
    "If operational composition is parenthesization-independent whenever a history
     uses at most two primitive distinction elements, then the scalar/unit
     composition sector must be associative and n=3 is selected."

Falsification:
    The octonions O = R + R^7 are alternative.  By Artin's theorem every
    subalgebra generated by any two elements is associative, while O itself is
    nonassociative.  Therefore all two-generator rebracketing tests can pass in
    n=7 even though a genuine three-generator associator is nonzero.

This cycle records the boundary as imported/known algebra, not PDT novelty.
"""
from __future__ import annotations

import itertools
import json
from pathlib import Path

import numpy as np

DIMS = list(range(1, 13)) + [16, 24, 32, 48, 64, 96, 128]


def conjugate(x: np.ndarray) -> np.ndarray:
    x = np.asarray(x)
    if x.ndim != 1 or x.size < 1 or x.size & (x.size - 1):
        raise ValueError("length must be a positive power of two")
    if x.size == 1:
        return x.copy()
    h = x.size // 2
    return np.concatenate((conjugate(x[:h]), -x[h:]))


def cd_mul(x: np.ndarray, y: np.ndarray) -> np.ndarray:
    """Cayley-Dickson product; exact on integer basis vectors through O."""
    x = np.asarray(x)
    y = np.asarray(y)
    if x.ndim != 1 or y.ndim != 1 or x.shape != y.shape:
        raise ValueError("equal one-dimensional shapes required")
    if x.size < 1 or x.size & (x.size - 1):
        raise ValueError("length must be a positive power of two")
    if x.size == 1:
        return x * y
    h = x.size // 2
    a, b = x[:h], x[h:]
    c, d = y[:h], y[h:]
    first = cd_mul(a, c) - cd_mul(conjugate(d), b)
    second = cd_mul(d, a) + cd_mul(b, conjugate(c))
    return np.concatenate((first, second))


def associator(x: np.ndarray, y: np.ndarray, z: np.ndarray) -> np.ndarray:
    return cd_mul(cd_mul(x, y), z) - cd_mul(x, cd_mul(y, z))


def canonical_three_generator_witness() -> dict:
    e = np.eye(8, dtype=int)
    a = associator(e[1], e[2], e[4])
    expected = np.zeros(8, dtype=int)
    expected[7] = 2
    return {
        "triple": [1, 2, 4],
        "associator": a.tolist(),
        "expected": expected.tolist(),
        "exact_match": bool(np.array_equal(a, expected)),
        "squared_norm": int(np.dot(a, a)),
        "norm": float(np.linalg.norm(a)),
    }


def basis_pair_subalgebra_audit() -> dict:
    """Audit all 21 imaginary-basis pairs.

    For each pair (ei,ej), test the four vectors {1,ei,ej,ei*ej}.  These form
    the quaternionic subalgebra generated by that pair.  All 4^3 basis
    associators are checked exactly with integer arithmetic.
    """
    e = np.eye(8, dtype=int)
    pair_rows = []
    total_triples = 0
    total_violations = 0
    for i in range(1, 8):
        for j in range(i + 1, 8):
            p = cd_mul(e[i], e[j])
            basis = np.stack((e[0], e[i], e[j], p))
            rank = int(np.linalg.matrix_rank(basis.astype(float)))
            violations = 0
            max_sq = 0
            for a, b, c in itertools.product(range(4), repeat=3):
                r = associator(basis[a], basis[b], basis[c])
                sq = int(np.dot(r, r))
                max_sq = max(max_sq, sq)
                violations += int(sq != 0)
            total_triples += 64
            total_violations += violations
            pair_rows.append({
                "pair": [i, j],
                "generated_basis_rank": rank,
                "product_ei_ej": p.tolist(),
                "tested_basis_triples": 64,
                "associator_violations": violations,
                "max_squared_associator_norm": max_sq,
            })
    return {
        "imaginary_basis_pairs": len(pair_rows),
        "tested_basis_triples_total": total_triples,
        "associator_violations_total": total_violations,
        "all_pair_generated_basis_subalgebras_associative": total_violations == 0,
        "rows": pair_rows,
    }


def _orthonormal_span(vectors: list[np.ndarray], tol: float = 1e-10) -> list[np.ndarray]:
    out: list[np.ndarray] = []
    for v in vectors:
        w = np.asarray(v, dtype=float).copy()
        for q in out:
            w -= q * float(np.dot(q, w))
        n = float(np.linalg.norm(w))
        if n > tol:
            out.append(w / n)
    return out


def generated_subalgebra_basis(x: np.ndarray, y: np.ndarray,
                               tol: float = 1e-10) -> np.ndarray:
    """Numerically close span{1,x,y} under multiplication."""
    one = np.zeros_like(np.asarray(x, dtype=float))
    one[0] = 1.0
    basis = _orthonormal_span([one, x, y], tol)
    for _ in range(8):
        old = len(basis)
        products = [cd_mul(a, b) for a in basis for b in basis]
        basis = _orthonormal_span(basis + products, tol)
        if len(basis) == old:
            break
    return np.stack(basis)


def random_two_generator_audit(pairs: int = 1000,
                               triples_per_pair: int = 12,
                               seed: int = 100_007) -> dict:
    rng = np.random.default_rng(seed)
    max_generated_rank = 0
    min_generated_rank = 8
    max_associator = 0.0
    violations = 0
    tested = 0

    for _ in range(pairs):
        x = rng.normal(size=8)
        y = rng.normal(size=8)
        basis = generated_subalgebra_basis(x, y)
        rank = len(basis)
        max_generated_rank = max(max_generated_rank, rank)
        min_generated_rank = min(min_generated_rank, rank)
        for _ in range(triples_per_pair):
            a = rng.normal(size=rank) @ basis
            b = rng.normal(size=rank) @ basis
            c = rng.normal(size=rank) @ basis
            residual = float(np.linalg.norm(associator(a, b, c)))
            max_associator = max(max_associator, residual)
            violations += int(residual > 1e-9)
            tested += 1

    return {
        "seed": seed,
        "random_generator_pairs": pairs,
        "random_triples_inside_generated_subalgebras": tested,
        "min_generated_subalgebra_rank": min_generated_rank,
        "max_generated_subalgebra_rank": max_generated_rank,
        "max_associator_residual": max_associator,
        "violations_gt_1e-9": violations,
    }


def dimension_ledger() -> list[dict]:
    """Scope audit over requested dimensions.

    A single exact n=7 counterexample falsifies the candidate implication.  For
    n not carrying one of the classical R/C/H/O scalar+imaginary normed
    division algebras, this specific counterexample family is not asserted.
    """
    classical = {1: "C (associative)", 3: "H (associative)", 7: "O (alternative; nonassociative)"}
    rows = []
    for n in DIMS:
        if n in classical:
            status = classical[n]
        else:
            status = "not a R/C/H/O imaginary-sector dimension; no claim from this family"
        rows.append({
            "distinction_vector_dimension_n": n,
            "audit_status": status,
            "candidate_n3_selector_survives_this_dimension": n == 7,
        })
    return rows


def generate() -> dict:
    exact_pairs = basis_pair_subalgebra_audit()
    witness = canonical_three_generator_witness()
    random_audit = random_two_generator_audit()
    return {
        "cycle": 100,
        "target": "PDT-II targets (1)/(2): can two-generator operational coherence select n=3?",
        "classification": [
            "PROVED",
            "FALSIFIED",
            "IMPORTED/KNOWN",
            "NUMERICALLY_SUPPORTED",
            "OPEN",
        ],
        "breakthrough_candidate": False,
        "candidate_statement": (
            "Parenthesization independence/coherence on every history generated "
            "by at most two primitive distinction elements is sufficient to force "
            "associative composition and select n=3."
        ),
        "falsification": {
            "result": "FALSIFIED",
            "counterexample_dimension_n": 7,
            "counterexample": (
                "Octonions O=R+R^7 are alternative: every two-generated "
                "subalgebra is associative, but O is globally nonassociative."
            ),
            "exact_basis_pair_audit": exact_pairs,
            "three_generator_witness": witness,
        },
        "randomized_stress": random_audit,
        "dimension_ledger": dimension_ledger(),
        "surviving_theorem": {
            "statement": (
                "Any composition test restricted to at most two generators "
                "cannot distinguish an alternative nonassociative algebra such "
                "as O from an associative algebra by rebracketing alone."
            ),
            "minimal_arity_needed_to_witness_octonionic_nonassociativity": 3,
            "qualification": (
                "Three-generator sensitivity is necessary for this route, not "
                "sufficient to make PDT associative unless PDT independently "
                "requires the associator to vanish for every triple."
            ),
        },
        "prior_art_boundary": (
            "Artin's theorem for alternative algebras states that every "
            "two-generated subalgebra is associative. Octonionic alternativity "
            "and quaternionic two-generator subalgebras are classical results; "
            "they are not PDT novelty."
        ),
        "open": (
            "Derive or falsify a PDT-native three-history/path-independence law "
            "from distinction and resource primitives. Do not assume full "
            "associativity merely to exclude n=7. Then test whether the law has "
            "a resource-indexed violation that can yield a same-input PDT-vs-QM "
            "prediction."
        ),
    }


if __name__ == "__main__":
    data = generate()
    path = Path("results/cycle100_two_generator_coherence_no_go.json")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(data, indent=2))
