"""Cycle 088: composition-stable dimension-3 no-go.

Target: PDT-II (2), a non-circular PDT-native n=3 derivation.

This module tests a necessary consistency condition that any universal
finite-dimensional system rule must satisfy if independent systems compose by
the ordinary tensor product.  It does NOT assume that elementary systems of a
particular type cannot have local dimension three.  It proves only that a rule
claiming that the Hilbert-space dimension of every allowed system is exactly
three is incompatible with tensor-composition closure.

The mathematical observation is elementary/known and is not claimed as a PDT
breakthrough.  Its value here is as a kill test that prevents a circular or
composition-inconsistent n=3 claim.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Dict, List

DIMS = list(range(1, 13)) + [16, 24, 32, 48, 64, 96, 128]
PRIMES = [2, 3, 5, 7, 11]


def tensor_dimension(d_a: int, d_b: int) -> int:
    """Hilbert-space dimension of an independent tensor composite."""
    if d_a < 1 or d_b < 1:
        raise ValueError("dimensions must be positive integers")
    return d_a * d_b


def tensor_power_dimensions(d: int, max_copies: int = 12) -> List[int]:
    """Dimensions d^k generated by repeated independent composition."""
    if d < 1 or max_copies < 1:
        raise ValueError("d and max_copies must be positive")
    return [d**k for k in range(1, max_copies + 1)]


def singleton_is_tensor_closed(d: int) -> bool:
    """Whether the singleton dimension class {d} is closed under tensoring."""
    return tensor_dimension(d, d) == d


def pure_quadratic_distinction(d: int) -> int:
    """Cycle-076/081 pure-state value E_d=d Tr(rho^2)-1=d-1."""
    if d < 1:
        raise ValueError("dimension must be positive")
    return d - 1


def audit_dimensions() -> List[Dict[str, int | bool]]:
    rows: List[Dict[str, int | bool]] = []
    for d in DIMS:
        rows.append(
            {
                "d": d,
                "tensor_square": d * d,
                "tensor_cube": d**3,
                "singleton_tensor_closed": singleton_is_tensor_closed(d),
                "pure_distinction": pure_quadratic_distinction(d),
                "pure_distinction_tensor_square": pure_quadratic_distinction(d * d),
            }
        )
    return rows


def prime_elementary_families(max_copies: int = 12) -> Dict[str, List[int]]:
    """Adversarial models showing tensor closure does not select prime 3.

    For every listed prime p, {1,p,p^2,...} has the same multiplicative closure
    pattern.  Hence interpreting 'n=3' as an elementary factor dimension does
    not follow from composition closure alone.
    """
    return {str(p): tensor_power_dimensions(p, max_copies) for p in PRIMES}


def run_audit() -> dict:
    rows = audit_dimensions()
    nontrivial_singleton_failures = [
        r["d"] for r in rows if r["d"] > 1 and not r["singleton_tensor_closed"]
    ]
    return {
        "cycle": 88,
        "title": "Composition-stable dimension-3 no-go",
        "target": "PDT-II (2) non-circular PDT-native n=3 derivation",
        "status": ["PROVED", "FALSIFIED", "NUMERICALLY_SUPPORTED", "IMPORTED/KNOWN"],
        "breakthrough_candidate": False,
        "theorem": (
            "If the allowed finite Hilbert-space dimensions are closed under independent "
            "tensor composition and contain d>1, then they contain d^k for every k>=1. "
            "Therefore no singleton {d} with d>1, in particular {3}, is tensor-composition closed."
        ),
        "smallest_decisive_counterexample": {
            "claimed_universal_dimension": 3,
            "two_copy_composite_dimension": tensor_dimension(3, 3),
        },
        "surviving_reinterpretation": (
            "Dimension three may still be proposed for an elementary/indecomposable system type, "
            "but composition closure alone cannot select it: p=2,3,5,7,11 all generate equally "
            "consistent power families under the same assumption."
        ),
        "dimensions": DIMS,
        "nontrivial_singleton_closure_failures": nontrivial_singleton_failures,
        "rows": rows,
        "prime_elementary_families": prime_elementary_families(),
        "prior_art_boundary": (
            "Composite-system capacity multiplication/information locality is standard in "
            "operational reconstructions; this cycle is a consistency no-go, not a historical novelty claim."
        ),
    }


if __name__ == "__main__":
    result = run_audit()
    out = Path("results/cycle088_composition_stable_dimension3_no_go.json")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(result, indent=2))
