"""Cycle 215: exact local-data composition no-go checks.

Finite/exact: no stochastic simulation and no floating-point arithmetic.
"""


def local_signature(n):
    """Only the constant local binary observable is admissible."""
    return tuple(0 for _ in range(n))


def min_signature(n):
    """Minimal composite closure generated by local constants."""
    return tuple(0 for _ in range(n * n))


def hol_signature(n):
    """Joint equality observable; nonlocal/holistic for n>=2."""
    return tuple(1 if x == y else 0 for x in range(n) for y in range(n))


def class_count(signatures):
    if not signatures:
        return 0
    m = len(signatures[0])
    return len({tuple(sig[i] for sig in signatures) for i in range(m)})


def run():
    rows = []
    for n in range(1, 13):
        loc = local_signature(n)
        assert class_count([loc]) == 1

        q_min = class_count([min_signature(n)])
        q_hol = class_count([min_signature(n), hol_signature(n)])

        assert q_min == 1
        if n == 1:
            assert q_hol == 1
            status = "EDGE/DEGENERATE"
        else:
            assert q_hol == 2
            status = "EXACT_COUNTEREXAMPLE"

        # Local declared families are literally identical in the two completions.
        same_local_data = True
        assert same_local_data
        rows.append((n, status, 1, 1, q_min, q_hol))
    return rows


if __name__ == "__main__":
    for row in run():
        print(row)
    print("Cycle 215 exact checks passed for n=1..12; obstruction holds for every n>=2.")
