"""Cycle 032: tensor-dimension closure no-go for PDT dimension selectors.

This module contains exact integer checks only.  It does not claim novelty.
"""

from __future__ import annotations


def tensor_dimension(a: int, b: int) -> int:
    """Ordinary finite-dimensional tensor composition: dim(A tensor B)=ab."""
    if a < 1 or b < 1:
        raise ValueError("dimensions must be positive integers")
    return a * b


def direct_sum_dimension(a: int, b: int) -> int:
    """Alternative extensive rule used as a robustness comparison."""
    if a < 1 or b < 1:
        raise ValueError("dimensions must be positive integers")
    return a + b


def tensor_power_ladder(d: int, copies: int) -> list[int]:
    """Dimensions d,d^2,...,d^copies generated by repeated tensoring."""
    if d < 1 or copies < 1:
        raise ValueError("d and copies must be positive")
    return [d**k for k in range(1, copies + 1)]


def sum_power_ladder(d: int, copies: int) -> list[int]:
    """Dimensions d,2d,...,copies*d generated by repeated direct sums."""
    if d < 1 or copies < 1:
        raise ValueError("d and copies must be positive")
    return [k * d for k in range(1, copies + 1)]


def is_tensor_closed(admissible: set[int]) -> bool:
    if any(d < 1 for d in admissible):
        raise ValueError("dimensions must be positive")
    return all(a * b in admissible for a in admissible for b in admissible)


def finite_tensor_selector_no_go(admissible: set[int]) -> bool:
    """True when a finite selector containing d>1 fails tensor closure.

    The theorem is elementary: if d>1 is admitted and tensor closure holds,
    then d^k is admitted for every k>=1; these are all distinct. Therefore a
    finite admissible set containing d>1 cannot be tensor closed.
    """
    if not admissible:
        return False
    if any(d < 1 for d in admissible):
        raise ValueError("dimensions must be positive")
    if not any(d > 1 for d in admissible):
        return False
    return not is_tensor_closed(admissible)


def universal_single_dimension_survives(d: int) -> bool:
    """Whether {d} is closed under ordinary tensor composition."""
    if d < 1:
        raise ValueError("dimension must be positive")
    return d * d == d


def extensive_self_composition_no_go(d: int, composed_dimension: int) -> bool:
    """One-step witness against a globally fixed dimension d.

    If self-composition has a strictly larger effective dimension, a universal
    rule requiring every system, including the composite, to have dimension d
    is inconsistent with that composition rule.
    """
    if d < 1 or composed_dimension < 1:
        raise ValueError("dimensions must be positive")
    return composed_dimension > d
