"""Cycle 124: rotationally covariant same-sector bilinear selector.

This module records an exact conditional theorem used as a PDT-II guard:
for n>=2, a nonzero SO(n)-equivariant bilinear map B: R^n x R^n -> R^n
exists only for n=3. Under full O(n) covariance every such bilinear map is zero.

The theorem is standard representation/invariant theory, so it is not claimed as
PDT novelty. Its role is to isolate precisely what an eventual PDT-native
composition derivation would have to provide.
"""
from __future__ import annotations

import numpy as np


def so_equivariant_bilinear_dimension(n: int) -> int:
    """Exact invariant-theory dimension of Hom_SO(n)(V tensor V, V).

    For n=1, SO(1) is trivial and ordinary scalar multiplication gives one
    dimension. For n>=2 the only nonzero case is n=3, generated by the cross
    product / Levi-Civita tensor.
    """
    if n < 1:
        raise ValueError("n must be positive")
    return 1 if n in (1, 3) else 0


def o_equivariant_bilinear_dimension(n: int) -> int:
    """Exact dimension under O(n): zero for every n>=1.

    Proof: -I belongs to O(n). Bilinearity gives B(-x,-y)=B(x,y), while
    equivariance gives B(-x,-y)=-B(x,y), hence B=0.
    """
    if n < 1:
        raise ValueError("n must be positive")
    return 0


def random_so(n: int, rng: np.random.Generator) -> np.ndarray:
    a = rng.normal(size=(n, n))
    q, r = np.linalg.qr(a)
    signs = np.sign(np.diag(r))
    signs[signs == 0.0] = 1.0
    q = q @ np.diag(signs)
    if np.linalg.det(q) < 0:
        q[:, 0] *= -1.0
    return q


def cross3_covariance_audit(seed: int = 124, trials: int = 1000) -> dict:
    """Numerically audit SO(3) covariance of the standard cross product."""
    rng = np.random.default_rng(seed)
    max_residual = 0.0
    violations = 0
    for _ in range(trials):
        r = random_so(3, rng)
        x = rng.normal(size=3)
        y = rng.normal(size=3)
        residual = np.linalg.norm(np.cross(r @ x, r @ y) - r @ np.cross(x, y))
        max_residual = max(max_residual, float(residual))
        if residual > 1e-10:
            violations += 1
    return {"seed": seed, "trials": trials, "violations": violations, "max_residual": max_residual}


def reflection_counterexample() -> dict:
    """Exact O(3) covariance failure for the cross product.

    R=diag(-1,1,1), x=e2, y=e3. Then (Rx)x(Ry)=e1 while R(xxy)=-e1.
    """
    r = np.diag([-1.0, 1.0, 1.0])
    x = np.array([0.0, 1.0, 0.0])
    y = np.array([0.0, 0.0, 1.0])
    lhs = np.cross(r @ x, r @ y)
    rhs = r @ np.cross(x, y)
    return {
        "det_R": float(np.linalg.det(r)),
        "lhs": lhs.tolist(),
        "rhs": rhs.tolist(),
        "residual_norm": float(np.linalg.norm(lhs - rhs)),
    }


def dimension_sweep(dimensions=tuple(range(1, 13)) + (16, 24, 32, 48, 64, 96, 128)) -> list[dict]:
    return [
        {
            "n": int(n),
            "dim_Hom_SO_VV_V": so_equivariant_bilinear_dimension(int(n)),
            "dim_Hom_O_VV_V": o_equivariant_bilinear_dimension(int(n)),
        }
        for n in dimensions
    ]
